[package]
name = "unit_convert"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
once_cell = "1.18.0"
regex = "1.9.6"
